# Generated by Django 4.0.4 on 2022-05-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, verbose_name='login')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('token', models.CharField(max_length=20, verbose_name='token')),
                ('mail', models.CharField(max_length=30, verbose_name='mail')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('profImg', models.ImageField(upload_to='profImg/', verbose_name='profImg')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('confirm', models.CharField(max_length=3, verbose_name='confirm')),
                ('dateTime', models.DateTimeField(auto_now=True, verbose_name='dateTime')),
            ],
        ),
    ]
